- apps/web/components/BottomNavbar.vue
- apps/web/components/TheHeader.vue
- apps/web/composables/useWishlist.ts
- apps/web/graphql/types.ts
- apps/web/server/queries/GetWishlist.ts
- apps/web/server/queries/index.ts
> fix: missing prop "collectedProducts"

- apps/web/components/checkout/AddressForm.vue
- apps/web/components/ui/OrderSummary.vue
- apps/web/composables/useAddress.ts
- apps/web/composables/useCountry.ts
- apps/web/composables/usePartner.ts
- apps/web/graphql/types.ts
- apps/web/pages/checkout.vue
- apps/web/server/fragments/addressFragment.ts
- apps/web/server/mutations/AddAddress.ts
- apps/web/server/mutations/CreateUpdatePartner.ts
- apps/web/server/mutations/UpdateAddress.ts
- apps/web/server/mutations/index.ts
- apps/web/server/queries/GetCountries.ts
- apps/web/server/queries/index.ts
add and update shipping and billing address
> 18092 shipping address

- apps/web/components/checkout/AddressForm.vue
- apps/web/pages/checkout.vue
Fix savedAddress props and partner email and name
> Delivery methods

- domains/category/components/CategoryFilterSidebar.vue
- domains/category/pages/category/[id].vue
> #18911 minor UI bugs

- domains/my-account/pages/my-account/my-orders.vue
- domains/orders/composable/useOrders.ts
- graphql/types.ts
- server/fragments/orderFragment.ts
- server/queries/GetOrderQuery.ts
- server/queries/GetOrdersQuery.ts
- server/queries/index.ts
Listing orders of an user at my-orders page.
> #18975 list orders of users

- domains/cart-redis/server/plugins/manage-cart.ts
- domains/checkout/components/ProviderAdyen.global.vue
- domains/product/pages/product/[slug].vue
improving order from product attributes on slug page
> improving order from product attributes on slug page

- domains/core/components/Newsletter.vue
- domains/core/components/ui/form/EmailInput.vue
- domains/core/composable/useCore.ts
- graphql/types.ts
- server/mutations/NewsletterSubscribeMutation.ts
- server/mutations/index.ts
Newsletter api and component update
> Newsletter

- Dockerfile
Fix Dockerfile node version to 20.10
> fix: dockerfile upgrade to node 20.10

- domains/cart-odoo/composables/useCart.ts
> refactor: 💡 updating cart odoo usecart to addmultipleitems

- domains/product/pages/product/[slug].vue
> fix: 🐛 fix product page product variant select attribute

- domains/auth/composables/useAuth.ts
reset email message and redireting user after request
> feat: 🎸 reset email message and redireting user after request

- domains/auth/composables/useAuth.ts
Using reset-password-success page instead ot toast message
> Using reset-password-success page instead ot toast message

- domains/auth/pages/reset-password-success.vue
> feat: 🎸 new page reset password success content

- domains/auth/composables/useAuth.ts
- domains/auth/pages/reset-password-success.vue
> Updating layout and content of reset password success page

- domains/auth/composables/useAuth.ts
- domains/auth/pages/forgot-password/new-password.vue
- domains/checkout/components/CheckoutContactInformation.vue
- graphql/gql/graphql.ts
- graphql/types.ts
> Closes #20058 and #19034

- domains/auth/composables/useAuth.ts
- domains/auth/pages/forgot-password/new-password.vue
Using corrent mutation on reset password
> [FIX] - Using corrent mutation on reset password

- domains/checkout/components/CheckoutHeader.vue
- domains/checkout/components/CheckoutPayment.vue
- domains/checkout/components/CheckoutShippingMethod.vue
- domains/checkout/components/CheckoutSummary.vue
- domains/checkout/pages/checkout.vue
- domains/core/components/ui/OrderSummary.vue
Improving checkout`s page maintainability
> refactor: 💡 checkout page

- domains/cart-redis/server/plugins/manage-cart.ts
(Cart doesn´t clean after a sale) https://pm.erpgap.com/projects/vuestorefront-api/work_packages/20028/activity
> Clearing cart from redis after payment success

- domains/cart-redis/server/plugins/manage-cart.ts
success after payment confirmation is now being tested
> fix: 🐛 success after payment confirmation is now being tested

- domains/cart-redis/server/plugins/manage-cart.ts
Testing inside manage-cart plugin just after getPaymentConfirmation query
> success after payment confirmation is now being tested

- domains/cart-redis/server/plugins/manage-cart.ts
- domains/checkout/components/CheckoutSummary.vue
- domains/checkout/composables/useDiscount.ts
- graphql/types.ts
- package.json
- yarn.lock
https://pm.erpgap.com/projects/vuestorefront-api/work_packages/20103/files
> Cart was not cleaning after gift cards payment

- package.json
> chore: 🤖 rollback odoo sdk version (test ci)

- package.json
> fixing nuxtjs device version after update packages

- domains/category/pages/category/[id].vue
- domains/category/utils/categoryHead.ts
- yarn.lock
retrieving category page seo meta
> fix: 🐛 #19730 - seo category page

- nuxt.config.ts
- package.json
- public/_robots.txt
- yarn.lock
trying manual nuxt robots file
> fix: 🐛 nuxt robots file

- nuxt.config.ts
- package.json
- public/_robots.txt
- yarn.lock
Reverts odoogap/storefront-ui#137
> Revert "fix: 🐛 nuxt robots file"

- nuxt.config.ts
- public/_robots.txt
> fix: 🐛 nuxt robot programmatically using nuxt config

- nuxt.config.ts
> fix: 🐛 adding a meta robots globally at app head

- domains/core/utils/websiteHomepageHead.ts
- pages/index.vue
It was needed remove onMounted from index page (homepage) and call the useHead directlly. Also homeSidePageHomeHead was improved to fix typescript errors
> fix: 🐛 seo at home page

- domains/core/components/TheFooter.vue
- domains/core/utils/websiteHomepageHead.ts
- nuxt.config.ts
when any page sends its own meta title, the title template is used
> feat: 🎸 defining a title template at nuxt config

- graphql/gql/fragment-masking.ts
- nuxt.config.ts
> fix: 🐛 removing title template at nuxt config head

- .loadtest/docker-compose.yaml
- .loadtest/tasks-odoo-website.py
- domains/category/components/CategoryFilterSidebar.vue
- domains/category/pages/category/[id].vue
- domains/recent-view-products/package.json
- nuxt.config.ts
> #20184 problems with slug

- domains/core/components/header/Desktop.vue
✅ Closes: 21317
https://pm.erpgap.com/projects/vuestorefront-api/work_packages/21317/activity?query_id=1
> fix: 🐛 search overlayer cant close

- domains/category/composables/useUiHelpers.ts
- domains/category/pages/category/[id].vue
✅ Closes: 21284
https://pm.erpgap.com/projects/vuestorefront-api/work_packages/21284/activity?query_id=1
> fix: 🐛 slash at end url doesnt work

- domains/product/pages/product/[slug].vue
✅ Closes: 21327
https://pm.erpgap.com/work_packages/21327/activity?query_id=1
> fix: 🐛 slash at end of product url doesnt work

- domains/cart-odoo/composables/useCart.ts
- domains/cart-odoo/pages/cart.vue
- domains/cart-redis/composables/useCart.ts
- domains/cart-redis/pages/cart.vue
- domains/cart-redis/server/utils/cartHelpers.ts
- domains/product/pages/product/[slug].vue
https://pm.erpgap.com/work_packages/20151/activity?query_id=1
> refactor: 💡 replace cart orderline by websiteorderline
